name: flutter_progress_dialog
description: A flutter library for the progress dialog. Easily show and hide. Support specify custom loading widget.
version: 0.2.0
homepage: https://github.com/wuzhendev/flutter_progress_dialog

environment:
  sdk: ^3.11.0
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
